import MainWrapper from "@/components/Wrappers/Client/MainWrapper";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <MainWrapper>
          <nav></nav>
          <main>{children}</main>
          <Toaster />
          <footer></footer>
        </MainWrapper>
      </body>
    </html>
  );
}
